SELECT ?city ?cityCountry ?inception (?inception as ?inceptionLabel) ?inceptionAltLabel
WHERE
{
  ?city wdt:P31 wd:Q1549591.
  ?city wdt:P17 ?country.
  ?city wdt:P571 ?inception.
  # Show both city and country to disambiguate
  BIND(CONCAT(?cityLabel, ", ", ?countryLabel) AS ?cityCountry).

  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en".
    ?city rdfs:label ?cityLabel.
    ?country rdfs:label ?countryLabel.
  }
}
